learning_template/basicapp/urls.py
'''from django.conf.urls import url
from basicapp import views


app_name='basicapp'

urlpatterns=[
             url(r'^relative/$',views.relative,name='relative'),
             url(r'^other/$',views.other,name='other'),
             


    ]
'''

learning_template/learning_template/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from basicapp import views 

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
#    url(r'^baicapp/',include('basicapp/urls'))
]

learning_template/basicapp/models.py
from django.db import models

# Create your models here.

learning_template/basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello','numnber':100}
    return render(request,'basicapp/index.html',context_dict)

def other(request):
    return render(request,'basicapp/other.html')

def relative(request):
    return render(request,'basicapp/relative_url_tempalte.html')


learning_template/templates/basicapp/base.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<nav class='navbar navbar-default navbar-static-top>
<div class='container'>
<ul class='nav navbar-nav'>
<li><a class='navbar-brand' href='#'>BRAND</a></li>
<li><a class='navbar-link' href='#'>Admin</a></li>
<li><a class='navbar-link' href='#'>Other</a></li> 
</ul>
</div>
</nav>

<div class='container'>
{% block body_block %}


{% endblock %}
</div>



</body>
</html>

learning_template/templates/basicapp/index.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>


<h1>Welcome to INDEX</h1>
{{text|upper}}
{{number}}


</body>
</html>

learning_template/templates/basicapp/other.html
<!DOCTYPE HTML>
{% extends 'basicapp/base.html' %}
{% block body_block %}
<!-- <html>
<head>
<meta charset="utf-8">
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
 -->

<h1>Welcome to OTHER!</h1>
<h2>This is an Example oif template inheritance</h2>
{% endblock %}


<!--</body>
</html>-->

learning_template/templates/basicapp/relative_url_template.html
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>


<h1>Welcome to RELATIVE URL TEMPLATE</h1>
<a href="{% url 'basicapp:other' %}">THE OTHER PAGE</a>


</body>
</html>